[JBPM-9308] EventEmitter is not working in spring boot
kiegroup/jbpm pull request #1738
Opened 2020-08-26 09:07 UTC by elguardian

JIRA: 
https://issues.redhat.com/browse/JBPM-9308

2020-08-26 13:49 UTC, afalhambra requested changes
Just a typo, everything else looks great.

2020-08-27 09:54 UTC, elguardian commented
Jenkins retest this please.

2020-08-28 09:43 UTC, elguardian commented on jbpm-persistence/jbpm-persistence-api/src/main/java/org/jbpm/persistence/api/integration/PersistenceEventManager.java
> +     * Override progamatically the emitter found
done

2020-08-28 10:23 UTC, afalhambra approved these changes
Nice work @elguardian, just wait for CI to clean.

2020-08-28 14:11 UTC, merged