[JBPM-9306] Raising exception when user is not defined
kiegroup/jbpm pull request #1740
Opened 2020-08-26 13:06 UTC by fjtirado

Currently If user does not exist in callback, the organizational entity
is not created, but no exception is thrown, so later a constraint
violation is thrown, as described in the JIRA.

Now the error message will be clear (the operation itself cannot suceed if the user is not in the context, we cannot allow arbitrary users to be added to organizationentity)

**JIRA**:

[JBPM-9306](https://issues.redhat.com/browse/JBPM-9306)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</pre>

2020-08-26 14:23 UTC, afalhambra requested changes
Just one typo.

I would also add a test to cover this scenario, where an exception is expected.

2020-08-26 14:23 UTC, afalhambra commented on jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/UserGroupCallbackTaskCommand.java
> +                    List<? extends Reassignment> ressignments = escalation.getReassignments();
typo

```suggestion
                    List<? extends Reassignment> reassignments = escalation.getReassignments();
```

2020-08-27 09:37 UTC, elguardian approved these changes
LGTM

2020-08-27 13:30 UTC, afalhambra approved these changes
Nice one. Good job

2020-08-28 08:55 UTC, fjtirado commented
@kiegroup/gatekeepers please merge this

2020-08-28 09:44 UTC, merged