[JBPM-9178] Immutable springboot images / adding the capability to re…
kiegroup/jbpm pull request #1749
Opened 2020-09-02 14:19 UTC by elguardian

Jira: https://issues.redhat.com/browse/JBPM-9178

2020-09-04 14:25 UTC, afalhambra requested changes
Looks good, nothing major, cosmetic changes.

2020-09-07 07:58 UTC, elguardian commented on jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/deploy/DeploymentDescriptorManagerUtil.java
> +        }
done

2020-09-07 07:58 UTC, elguardian commented on jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/deploy/DeploymentDescriptorManagerUtil.java
> +                logger.debug("Error when closing stream of kie-deployment-descriptor.xml");
ok

2020-09-07 07:58 UTC, elguardian commented on jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/deploy/DeploymentDescriptorManagerUtil.java
> +                    logger.warn("Cound not read deployment descriptor on classpath", e);
ok

2020-09-07 09:14 UTC, afalhambra commented on jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/deploy/DeploymentDescriptorManagerUtil.java
> +                logger.debug("Error when closing stream of kie-deployment-descriptor.xml");
I can't see this yet?

2020-09-07 09:17 UTC, afalhambra requested changes
Sorry, can't see the change you marked as "resolved" to add more details about the IOException in the warning log

https://github.com/kiegroup/jbpm/blob/d090fe4588afd8b585405e4e9d96b51dcf2d296e/jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/deploy/DeploymentDescriptorManagerUtil.java#L95

2020-09-07 09:21 UTC, elguardian commented
> Sorry, can't see the change you marked as "resolved" to add more details about the IOException in the warning log
> 
> https://github.com/kiegroup/jbpm/blob/d090fe4588afd8b585405e4e9d96b51dcf2d296e/jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/deploy/DeploymentDescriptorManagerUtil.java#L95

Aside to set is as warn there is no point as that is in memory descriptor already. so the only possibility is a failure in the parsing.

2020-09-07 09:39 UTC, afalhambra approved these changes
Great work, really hope this is the last change regarding immutable springboot :)

2020-09-08 06:30 UTC, merged