[JBPM-9407] Spring Boot - Multiple Data Sources and Pluggable Variable Persistence
kiegroup/jbpm pull request #1769
Opened 2020-10-06 13:10 UTC by elguardian

Jira https://issues.redhat.com/browse/JBPM-9407

Moving the code required for objects creating to a method so it could be overwritten

2020-10-13 10:02 UTC, elguardian commented
Jenkins retest this please.

2020-10-14 00:15 UTC, gmunozfe approved these changes
Looks good to me, though a javadoc explaining the purpose of the protected method would be helpful.

2020-10-28 08:49 UTC, afalhambra requested changes
only a typo. Otherwise, it looks good to me.

2020-10-28 08:49 UTC, afalhambra commented on jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/KModuleDeploymentService.java
> +		Map<String, Object> contaxtParams = buildContextParameters(kieContainer);
typo
```suggestion
		Map<String, Object> contextParams = buildContextParameters(kieContainer);
```

2020-10-29 08:17 UTC, elguardian commented on jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/KModuleDeploymentService.java
> +		Map<String, Object> contaxtParams = buildContextParameters(kieContainer);
done

2020-10-29 09:31 UTC, afalhambra approved these changes
Nice work

2020-11-09 14:07 UTC, merged