[JBPM-9465] Add support for using the public API to retrieve a node type
kiegroup/jbpm pull request #1804
Opened 2020-11-13 17:22 UTC by fjtirado

Implementing getNodeType

**JIRA**: 

[JBPM-9465]( https://github.com/fjtirado/droolsjbpm-knowledge/pull/new/JBPM-9465)

2020-11-13 17:35 UTC, fjtirado commented
jenkins retest this

2020-11-16 08:40 UTC, elguardian commented
jenkins retest this

2020-11-17 10:03 UTC, gmunozfe reviewed
Shouldn't AsyncEventNode also include the type of node?
Missing one test for THROW_EVENT

2020-11-17 10:57 UTC, elguardian commented
Jenkins retest this

2020-11-17 11:11 UTC, gmunozfe commented on jbpm-flow/src/test/java/org/jbpm/workflow/core/node/NodeTypeTest.java
> +package org.jbpm.workflow.core.node;
Missing header

2020-11-17 11:11 UTC, gmunozfe requested changes
Missing header in new test class.

Also following compilation errors:
```
[ERROR] ../jbpm/jbpm-flow/src/test/java/org/jbpm/workflow/core/node/NodeInnerClassesTest.java org.jbpm.workflow.core.node.CompositeNode is abstract; cannot be instantiated
[ERROR] ../jbpm/jbpm-flow/src/test/java/org/jbpm/ruleflow/core/validation/RuleFlowProcessValidatorTest.java:[188,39] org.jbpm.workflow.core.node.CompositeNode is abstract; cannot be instantiated
[ERROR] ../jbpm/jbpm-flow/src/test/java/org/jbpm/process/EventTest.java:[754,39] org.jbpm.workflow.core.node.CompositeNode is abstract; cannot be instantiated
```

2020-11-17 16:05 UTC, fjtirado commented
jenkins retest this

2020-11-18 09:32 UTC, gmunozfe commented
These tests

- org.jbpm.process.CompensationTest.testCompensationEventSubProcessSpecific
- org.jbpm.process.CompensationTest.testNestedCompensationBoundaryEventGeneral
- org.jbpm.process.CompensationTest.testNestedCompensationEventSubProcessSpecific
- org.jbpm.process.CompensationTest.testCompensationEventSubProcessGeneral
- org.jbpm.process.CompensationTest.testCompensationBoundaryEventGeneral
- org.jbpm.process.CompensationTest.testNestedCompensationBoundaryEventSpecific
- org.jbpm.process.CompensationTest.testNestedCompensationEventSubProcessGeneral
- org.jbpm.process.CompensationTest.testCompensationBoundaryEventSpecific
- org.jbpm.process.EventSubProcessTest.testNestedEventSubProcess


 are failing with 
```
java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jbpm.process.test.NodeCreator.createNode(NodeCreator.java:41)
```

One of the possible fixes is this (in _createNode_ method of **NodeCreator** class):

`T result = this.constructor.newInstance(new Object[this.constructor.getParameterCount()]);`

2020-11-18 10:55 UTC, afalhambra commented
Jenkins retest this

2020-11-18 11:54 UTC, afalhambra requested changes
Very nice one @fjtirado - just small changes required for the access to a protected constructor

2020-11-18 11:54 UTC, afalhambra commented on jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/IntermediateThrowEventHandler.java
> +        return new ActionNode(NodeType.THROW_EVENT);
Compilation error - this constructor has `protected` access only

2020-11-18 11:54 UTC, afalhambra commented on jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/ScriptTaskHandler.java
> +        ActionNode result = new ActionNode(NodeType.SCRIPT_TASK);
Compilation error - this constructor has `protected` access only

2020-11-18 13:12 UTC, afalhambra approved these changes
Just wait for CI to turn green :)

2020-11-18 16:52 UTC, fjtirado commented
run fdb

2020-11-23 09:21 UTC, gmunozfe approved these changes
Looks good to me, fantastic work @fjtirado !

2020-11-23 13:50 UTC, merged