JBPM-9469 - Task inputs are not updated in TaskVariableImpl table aft…
kiegroup/jbpm pull request #1805
Opened 2020-11-16 18:51 UTC by MarianMacik

…er the task is updated

[JBPM-9469](https://issues.redhat.com/browse/JBPM-9469)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

2020-11-17 07:36 UTC, elguardian commented
@MarianMacik failure related.

2020-11-17 10:34 UTC, elguardian requested changes
null pointer. requires assesment

2020-11-18 13:09 UTC, afalhambra reviewed
Very good job @MarianMacik . Thanks for this! 
Just only two comments:

- Shouldn't we add (or modify) a test to update an input task variable twice? so we make sure it gets updated properly? - wdyt?
- The only other issue that comes to my mind is about any potential performance downgrade when it comes to using the new api for advanced queries (only when updating input task vars). Though... at the same time, performance wise should now be consistent with output task variables use

2020-11-18 13:46 UTC, MarianMacik commented
>     * Shouldn't we add (or modify) a test to update an input task variable twice? so we make sure it gets updated properly? - wdyt?
As I said in the description, in case an already-existing input is overwritten (updated twice), there will be another task variable impl record in the table, I guess we may consider enhancing it in a separate PR after we test any possible performance degradation caused by one more delete query (as the same piece of code is used when the task is added for example, that would impact pretty much all operations then).

>     * The only other issue that comes to my mind is about any potential performance downgrade when it comes to using the new api for advanced queries (only when updating input task vars). Though... at the same time, performance wise should now be consistent with output task variables use
My understanding was that it was a bug as newly-added inputs or overwritten inputs weren't even queried as they were not visible in the database. So in that case it was a bug I would say.

2020-11-18 13:47 UTC, MarianMacik commented
Jenkins retest this

2020-11-18 14:25 UTC, afalhambra commented
> > ```
> > * Shouldn't we add (or modify) a test to update an input task variable twice? so we make sure it gets updated properly? - wdyt?
> > ```
> 
> As I said in the description, in case an already-existing input is overwritten (updated twice), there will be another task variable impl record in the table, I guess we may consider enhancing it in a separate PR after we test any possible performance degradation caused by one more delete query (as the same piece of code is used when the task is added for example, that would impact pretty much all operations then).
> 

Regardless of performance, for this particular PR, I was more thinking about a particular test case for updating the input variable twice and afterwards fetching the input tasks and making sure the value retrieved is the latest one - I believe this scenario is not covered in any of the tests? or am I wrong?

2020-11-18 15:00 UTC, MarianMacik commented
So you meant to update the input twice and just check it is overwritten when `userTaskService.getTaskInputContentByTaskId(taskId);` is called? I can do that though it works as inputs are map-based and new inputs are just added there via put. Though as I said, in task variable impl table there will be both the previous and the current value present.

2020-11-18 17:34 UTC, MarianMacik commented
@afalhambra It is green now. Do you want me to add another test case? But I personally don't see the benefit of it.

2020-11-19 07:39 UTC, afalhambra approved these changes
Sorry @MarianMacik, I didn't notice that even new input task vars were not being taken into account at first place, that's why I was asking. 
Looks very great to me! thanks @MarianMacik!

2020-11-19 07:59 UTC, MarianMacik commented
> Sorry @MarianMacik, I didn't notice that even new input task vars were not being taken into account at first place, that's why I was asking.

New are taken into account, so if you add a new input task A with value "a" it will be shown. When you then update the task with the same input A with value "b", it will be added (and not overwritten) in the task variable impl table. So you will be able to query the task based on the new and old value ("a" and "b"). To fix that, we would have to run delete query first, which was there, but was removed because of perf issues - as that query in the listener would have to be run also when the task is created for example. That's why I chose to make a compromise, so you are now able to add new inputs and query tasks based on them. If you, however, overwrite it, the old value is still available, because delete wasn't called. I may try to improve it next sprint if I have time.

2020-11-19 08:18 UTC, afalhambra commented
Yes, it's pretty cleared now, thanks! - it might have some impact in the perf (specially when querying), but we can deal with it later on. I will be running some perf test to see.

2020-11-20 08:07 UTC, elguardian commented
This makes sense to me as allow the system to be consistent in database. otherwise you would see "magic changes" in the  database without any audit.
We cannot sacrifice correctness over speed. And in this case the command is not that widely use.

2020-11-20 08:07 UTC, elguardian approved these changes

2020-11-20 08:08 UTC, merged