[JBPM-9619] Task inbox fails to display data due to inefficient query
kiegroup/jbpm pull request #1870
Opened 2021-02-18 19:44 UTC by fjtirado

Adding index for oracle

**JIRA**: 

[link](https://issues.redhat.com/browse/JBPM-9619)

2021-02-19 00:45 UTC, cristianonicolai approved these changes

2021-02-22 07:51 UTC, elguardian requested changes
DDL and upgrade scripts are required.

2021-02-22 10:43 UTC, fjtirado commented
As explained to @elguardian, I was just changing the Oracle files so Martin can test. 
First test indicate that actualOwner does not make a significant performance improvement with currrent query. We are doing further investigation. Moving into draft

2021-03-03 11:54 UTC, fjtirado commented
jenkins run fdb

2021-03-04 10:28 UTC, merged