[JBPM-9735] Improve jbpm engine Message and Signal
kiegroup/jbpm pull request #1943
Opened 2021-05-31 10:44 UTC by elguardian

Jira: https://issues.redhat.com/browse/JBPM-9735

2021-06-03 06:40 UTC, elguardian commented
Jenkins retest this please

2021-06-07 10:11 UTC, elguardian commented
Jenkins retest this please

2021-06-08 15:16 UTC, gmunozfe requested changes
Looks good to me, huge and fabulous work @elguardian !
Check some typos (especially with metadata) and other minor comments.
It'd be great to add some more testing regarding edge conditions or events catching in subprocesses.

2021-06-09 10:36 UTC, elguardian commented on jbpm-flow/src/main/java/org/jbpm/process/core/correlation/Correlation.java
> +        return correlationPropertiesByMessage.computeIfAbsent(messageRef, (ref) -> new CorrelationProperties());
done

2021-06-09 10:37 UTC, elguardian commented on jbpm-flow/src/main/java/org/jbpm/process/core/correlation/CorrelationInstance.java
> +        if(properties.size() != other.properties.size()) {
that cannot happen as constructor will have always an empty map at least

2021-06-09 10:37 UTC, elguardian commented on jbpm-flow/src/main/java/org/jbpm/process/core/correlation/Message.java
> +public class Message {
yep

2021-06-09 10:38 UTC, elguardian commented on jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/core/CorrelationKey.java
> +public class CorrelationKey {
yep

2021-06-09 10:38 UTC, elguardian commented on jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/core/Collaboration.java
> +public class Collaboration {
yep

2021-06-09 10:38 UTC, elguardian commented on jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/core/CorrelationSubscription.java
> +public class CorrelationSubscription {
yep

2021-06-09 10:39 UTC, elguardian commented on jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/CollaborationHandler.java
> +        for(int i = 0; i < childNodes.getLength(); i++) {
done

2021-06-09 10:39 UTC, elguardian commented on jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/CollaborationHandler.java
> +                propertiesRef.add(node.getTextContent().trim());
removed

2021-06-09 10:40 UTC, elguardian commented on jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/HandlerUtil.java
> +    public static Map<String, ItemDefinition> defintions(ExtensibleXmlParser parser) {
done

2021-06-09 10:40 UTC, elguardian commented on jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/HandlerUtil.java
> + * Copyright 2017 Red Hat, Inc. and/or its affiliates.
done

2021-06-09 10:40 UTC, elguardian commented on jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/HandlerUtil.java
> +        if(definitions == null) {
done

2021-06-09 10:41 UTC, elguardian commented on jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/HandlerUtil.java
> +        if(properties == null) {
done

2021-06-09 10:41 UTC, elguardian commented on jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/HandlerUtil.java
> +        if(correlationSuscription == null) {
done

2021-06-09 10:41 UTC, elguardian commented on jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/HandlerUtil.java
> +        Map<String, CorrelationSubscription> correlationSuscription = (Map<String, CorrelationSubscription>) process.getMetaData("CorrelationSuscriptions");
done

2021-06-09 10:41 UTC, elguardian commented on jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/HandlerUtil.java
> +            process.setMetaData("CorrelationSuscriptions", correlationSuscription);
done

2021-06-09 10:43 UTC, elguardian commented on jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/StartEventHandler.java
> +                addTriggerWithInMappings(startNode, "Message-" + message.getName(), message.getId(), ((RuleFlowProcess) parser.getMetaData().get("CurrentProcessDefintion")).getCorrelationManager());
done

2021-06-09 10:44 UTC, elguardian commented on jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/BoundaryEventHandler.java
> +                eventFilter.setCorrelationManager(((RuleFlowProcess) parser.getMetaData().get("CurrentProcessDefintion")).getCorrelationManager());
done

2021-06-09 10:44 UTC, elguardian commented on jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/IntermediateCatchEventHandler.java
> +                eventFilter.setCorrelationManager(((RuleFlowProcess) parser.getMetaData().get("CurrentProcessDefintion")).getCorrelationManager());
done

2021-06-09 10:44 UTC, elguardian commented on jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/ProcessHandler.java
> +		parser.getMetaData().put("CurrentProcessDefintion", process);
done

2021-06-09 10:45 UTC, elguardian commented on jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/ProcessHandler.java
> +        Collection<CorrelationSubscription> subscriptions = HandlerUtil.correlationSuscription(process).values();
removed

2021-06-09 10:45 UTC, elguardian commented on jbpm-flow/src/main/java/org/jbpm/process/core/correlation/CorrelationManager.java
> +        throw new IllegalArgumentException("Correlation for message ref " + messageRef + " does not exists");
done

2021-06-09 10:48 UTC, elguardian commented on jbpm-flow/src/main/java/org/jbpm/process/core/event/EventTypeFilter.java
> +            if(correlationManager != null && correlationManager.isSubscribe(messageRef)) {
done

2021-06-09 10:48 UTC, elguardian commented on jbpm-flow/src/main/java/org/jbpm/process/core/event/MVELMessageExpressionEvaluator.java
> +            public boolean isResolveable(String name) {
added

2021-06-09 10:48 UTC, elguardian commented on jbpm-flow/src/main/java/org/jbpm/process/core/event/MVELMessageExpressionEvaluator.java
> +            public VariableResolver getVariableResolver(String name) {
added

2021-06-09 11:07 UTC, elguardian commented on jbpm-test-coverage/src/test/java/org/jbpm/test/functional/collaboration/CollaborationTest.java
> +
added

2021-06-10 08:06 UTC, gmunozfe reviewed
Just missing one class to be serializable and a little typo in an exception message

2021-06-10 08:06 UTC, gmunozfe commented on jbpm-flow/src/main/java/org/jbpm/process/core/correlation/CorrelationManager.java
> +        throw new IllegalArgumentException("Correlation for message ref " + messageRef + " does not exists");
I think you didn't commit, seeing still the typo

2021-06-10 13:32 UTC, elguardian commented on jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/core/Collaboration.java
> +public class Collaboration {
this case is not needed. but ok (it belongs to the parser)

2021-06-11 06:40 UTC, elguardian commented
Jenkins retest this please.

2021-06-14 06:29 UTC, merged