[JBPM-9877] Revert schema changes for DB partition
kiegroup/jbpm pull request #2006
Opened 2021-08-31 07:11 UTC by elguardian

Jira: https://issues.redhat.com/browse/JBPM-9877

2021-08-31 08:27 UTC, gmunozfe requested changes
Check compilation error (end doesn't exist):
https://github.com/kiegroup/jbpm/blob/fdb0059ce00a327f0e29ba54d1484709f17229d3/jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/audit/impl/model/TaskEventImpl.java#L240

2021-08-31 08:43 UTC, gmunozfe commented
ArchiveLoggerProvider is not removed, but any service won't be loaded at JPAWorkingMemoryDbLogger.java by default, is it expected behavior?

2021-08-31 08:49 UTC, gmunozfe commented
Upgrade community db scripts adding "end_date" columns (jbpm-7.56-to-7.57.sql) should remove these columns in the same way (jbpm-7.59-to-7.60.sql), wdyt?

2021-09-02 12:55 UTC, gmunozfe requested changes
Looks good, I've just detected a missing removal column (end_date) for AuditTaskImpl at oracle-springboot-jbpm-schema.sql

2021-09-03 06:34 UTC, elguardian commented on jbpm-db-scripts/src/main/resources/db/ddl-scripts/oracle/oracle-springboot-jbpm-schema.sql
>  create table AuditTaskImpl (id number(19,0) not null, activationTime timestamp, actualOwner varchar2(255 char), createdBy varchar2(255 char), createdOn timestamp, deploymentId varchar2(255 char), des
you are right

2021-09-03 08:15 UTC, gmunozfe approved these changes
Looks good to me, amazing work @elguardian !

2021-09-03 09:04 UTC, merged