[JBPM-9887] Getting the process id out of the ejb timer column
kiegroup/jbpm pull request #2019
Opened 2021-09-14 07:25 UTC by elguardian

Jira: https://issues.redhat.com/browse/JBPM-9887

2021-09-22 08:34 UTC, elguardian commented
Jenkins retest this please

2021-09-23 09:21 UTC, elguardian commented
Jenkins retest this please

2021-10-04 09:50 UTC, afalhambra requested changes
Some minor comments in the code, please have a look at some requested changes in the sql scripts.
Would be good if you could please add a unit or integration test here or in the integration repo.

2021-10-04 09:50 UTC, afalhambra commented on jbpm-db-scripts/src/main/resources/db/ddl-scripts/db2/db2-jbpm-schema.sql
> +    	id bigint generated by default as entity,
typo
```suggestion
    	id bigint generated by default as identity, 
```

2021-10-04 09:50 UTC, afalhambra commented on jbpm-db-scripts/src/main/resources/db/ddl-scripts/derby/derby-jbpm-schema.sql
> +    	id bigint generated by default as entity,
typo
```suggestion
    	id bigint generated by default as identity, 
```

2021-10-04 09:50 UTC, afalhambra commented on jbpm-db-scripts/src/main/resources/db/ddl-scripts/hsqldb/hsqldb-jbpm-schema.sql
> +    	id bigint generated by default as entity (start with 1),
typo
```suggestion
    	id bigint generated by default as identity (start with 1), 
```

2021-10-04 09:50 UTC, afalhambra commented on jbpm-db-scripts/src/main/resources/db/ddl-scripts/oracle/oracle-springboot-jbpm-schema.sql
> +alter table TimerMappingInfo add constraint IDX_TMI_KSessionUUID unique (kieSessionId, uuid);
This should be a `create index` instead of `alter table`

2021-10-04 09:50 UTC, afalhambra commented on jbpm-db-scripts/src/main/resources/db/ddl-scripts/postgresql/postgresql-bytea-jbpm-schema.sql
> +create table CorrelationKeyInfo (keyId int8 not null, name varchar(255), processInstanceId int8 not null, OPTLOCK int4, primary key (keyId));
please, revert this change

2021-10-04 09:50 UTC, afalhambra commented on jbpm-db-scripts/src/main/resources/db/ddl-scripts/postgresql/postgresql-bytea-jbpm-schema.sql
> +alter table TimerMappingInfo add constraint IDX_TMI_KSessionUUID unique (kieSessionId, uuid);
Same, this should be a `create index` instead of `alter table` statement

2021-10-04 09:50 UTC, afalhambra commented on jbpm-db-scripts/src/main/resources/db/ddl-scripts/postgresql/postgresql-jbpm-drop-schema.sql
> +alter table Delegation_delegates drop constraint FKewkdyi0wrgy9byp6abyglpcxq;
please revert these changes not related to the PR

2021-10-04 09:50 UTC, afalhambra commented on jbpm-db-scripts/src/main/resources/db/ddl-scripts/postgresql/postgresql-springboot-bytea-jbpm-schema.sql
> +create table CorrelationKeyInfo (keyId int8 not null, name varchar(255), processInstanceId int8 not null, OPTLOCK int4, primary key (keyId));
Please revert this change

2021-10-04 09:50 UTC, afalhambra commented on jbpm-db-scripts/src/main/resources/db/ddl-scripts/postgresql/postgresql-springboot-bytea-jbpm-schema.sql
> +alter table TimerMappingInfo add constraint IDX_TMI_KSessionUUID unique (kieSessionId, uuid);
this should be a `create index` and not an `alter table`

2021-10-04 09:50 UTC, afalhambra commented on jbpm-db-scripts/src/main/resources/db/ddl-scripts/postgresql/postgresql-springboot-jbpm-schema.sql
> +create table CorrelationKeyInfo (keyId int8 not null, name varchar(255), processInstanceId int8 not null, OPTLOCK int4, primary key (keyId));
Please revert this change

2021-10-04 09:50 UTC, afalhambra commented on jbpm-db-scripts/src/main/resources/db/ddl-scripts/postgresql/postgresql-springboot-jbpm-schema.sql
> +alter table TimerMappingInfo add constraint IDX_TMI_KSessionUUID unique (kieSessionId, uuid);
same regarding alter table, should be create index

2021-10-04 09:50 UTC, afalhambra commented on jbpm-db-scripts/src/main/resources/db/ddl-scripts/sqlserver/sqlserver-springboot-jbpm-schema.sql
> +alter table TimerMappingInfo add constraint IDX_TMI_KSessionUUID unique (kieSessionId, uuid);
should be a create index

2021-10-04 09:50 UTC, afalhambra commented on jbpm-db-scripts/src/main/resources/db/upgrade-scripts/db2/jbpm-7.60-to-7.61-TimerMappingInfo.sql
> +
Just curious, why are we naming this file with suffix `TimerMappingInfo`? is it because this is optional?

2021-10-04 09:50 UTC, afalhambra commented on jbpm-db-scripts/src/main/resources/db/upgrade-scripts/db2/jbpm-7.60-to-7.61-TimerMappingInfo.sql
> +	id bigint generated by default as entity,
```suggestion
	id bigint generated by default as identity, 
```

2021-10-04 09:50 UTC, afalhambra commented on jbpm-db-scripts/src/main/resources/db/upgrade-scripts/db2/rhpam-7.12-to-7.13.sql
> +	id bigint generated by default as entity,
```suggestion
	id bigint generated by default as identity, 
```

2021-10-04 09:50 UTC, afalhambra commented on jbpm-db-scripts/src/main/resources/db/upgrade-scripts/derby/jbpm-7.60-to-7.61-TimerMappingInfo.sql
> +	id bigint generated by default as entity,
```suggestion
	id bigint generated by default as identity, 
```

2021-10-04 09:50 UTC, afalhambra commented on jbpm-db-scripts/src/main/resources/db/upgrade-scripts/derby/rhpam-7.12-to-7.13.sql
> +	id bigint generated by default as entity,
```suggestion
	id bigint generated by default as identity, 
```

2021-10-04 09:50 UTC, afalhambra commented on jbpm-db-scripts/src/main/resources/db/upgrade-scripts/hsqldb/jbpm-7.60-to-7.61-TimerMappingInfo.sql
> +	id bigint generated by default as entity,
```suggestion
	id bigint generated by default as identity, 
```

2021-10-04 09:50 UTC, afalhambra commented on jbpm-db-scripts/src/main/resources/db/upgrade-scripts/hsqldb/rhpam-7.12-to-7.13.sql
> +	id bigint generated by default as entity,
```suggestion
	id bigint generated by default as identity, 
```

2021-11-02 08:00 UTC, elguardian commented
Jenkins retest this please

2021-11-02 09:19 UTC, afalhambra approved these changes
Great work @elguardian!

2021-11-08 11:32 UTC, merged