[JBPM-9939] Text contributor for @Lob String fields
kiegroup/jbpm pull request #2059
Opened 2021-11-09 10:14 UTC by elguardian

Jira: https://issues.redhat.com/browse/JBPM-9939

2021-11-10 08:43 UTC, elguardian commented
Jenkins retest this please

2021-11-11 13:52 UTC, elguardian commented
Jenkins retest this please.

2021-11-12 07:47 UTC, elguardian commented
Jenkins retest this please

2021-11-15 07:34 UTC, elguardian commented
Jenkins retest this please.

2021-11-23 16:58 UTC, martinweiler requested changes

2021-11-23 16:58 UTC, martinweiler commented on jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/jpa/hibernate/PostgreSQLByteaTypeContributor.java
> +            typeContributions.contributeType(new TextContributorType());
Please add a system property to enable the TextContributorType for backwards compatibility when running against an existing database. By default, it should not be enabled.

2021-11-26 12:52 UTC, afalhambra requested changes
Great work @elguardian - just need to ask for a test :)

2021-11-29 07:39 UTC, elguardian commented
@afalhambra merging this one and opening a new jira for that test case (discussion)

2021-11-29 07:39 UTC, merged