[JBPM-10001] Variable name might be null in IntermediateThrowHandler
kiegroup/jbpm pull request #2090
Opened 2022-01-26 19:06 UTC by fjtirado

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

2022-01-26 19:26 UTC, fjtirado commented on jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/IntermediateThrowEventHandler.java
> +                if (v != null) {
In previous implementation if Variable was not null but Variable.getMedata(mappingVariable) was, then rather that use mappingVariable (as I think should be the case) we will be setting varName to null. 
This makes the message object used by the action (which is also used for Kafka  extension) null.

2022-01-27 07:12 UTC, gmunozfe requested changes

2022-01-27 07:12 UTC, gmunozfe commented on jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/IntermediateThrowEventHandler.java
> +                if (text.startsWith("\"") && text.endsWith("\"")) {
Compilation error, missing closing bracket:
[ERROR] /home/jenkins/workspace/KIE/main/pullrequest/jbpm-main.pr/bc/kiegroup_jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/IntermediateThrowEventHandler.java:[382,9] illegal start of expression

2022-01-27 11:18 UTC, fjtirado commented on jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/IntermediateThrowEventHandler.java
> +                String varName = (String) actionNode.getMetaData("MappingVariable");
The var name should be retireved in the same way than in EndEventHandler

2022-01-27 15:30 UTC, gmunozfe approved these changes
Looks good to me, well done @fjtirado !

2022-01-27 17:34 UTC, merged