[JBPM-10016] Drools/jBPM integration: high number of instances waitin…
kiegroup/jbpm pull request #2105
Opened 2022-02-11 09:32 UTC by mariofusco

…g for signal adversely impacts execution time

2022-02-14 07:41 UTC, elguardian approved these changes

2022-02-15 10:47 UTC, gmunozfe commented
@mariofusco, add the reference to the drools PR in the description: https://github.com/kiegroup/drools/pull/4196

2022-02-15 11:52 UTC, gmunozfe requested changes
It's not working as expected: the 3 threads are taking the same batch, instead of distributing the load among them, @elguardian could you take a look?

2022-02-15 12:17 UTC, elguardian commented on jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/processinstance/JPASignalManager.java
>  package org.jbpm.persistence.processinstance;
@mariofusco  do you mind to remove this file change. I will treat the batch system in a different PR.

2022-02-16 07:58 UTC, elguardian commented on jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/processinstance/JPASignalManager.java
>  package org.jbpm.persistence.processinstance;
yes. it should

2022-02-16 07:58 UTC, elguardian commented on jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/processinstance/JPASignalManager.java
>  package org.jbpm.persistence.processinstance;
@mariofusco

2022-02-17 07:56 UTC, merged