[JBPM-10020]-Add incrementing and decrementing prometheus metric for …
kiegroup/jbpm pull request #2107
Opened 2022-02-16 18:45 UTC by VaniHaripriya

JIRA- https://issues.redhat.com/browse/JBPM-10020

Created a new command to throw execution error to use it for testing a new prometheus metric created for kie server execution errors.

Related Pull Request:

2022-02-17 08:03 UTC, elguardian commented on jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/commands/JobExecutionErrorCommand.java
> +
this won't add up as an error as you are catching the null pointer. to simulate an error you just can
throw new RuntimeException()

2022-02-17 08:33 UTC, gmunozfe requested changes

2022-02-17 08:33 UTC, gmunozfe commented on jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/commands/JobExecutionErrorCommand.java
> +    	ctx = null; //Assigning null value to throw null pointer exception
this assignment is not correct, better follow Enrique's approach.

2022-02-17 16:39 UTC, gmunozfe commented on jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/commands/JobExecutionErrorCommand.java
> + * Copyright 2017 Red Hat, Inc. and/or its affiliates.
```suggestion
 * Copyright 2022 Red Hat, Inc. and/or its affiliates.
```

2022-02-17 16:47 UTC, VaniHaripriya commented
> If this is for testing, shouldn't it be at "test" folder instead of "main"?

Agree with you @gmunozfe , will move it to test folder.

2022-02-21 07:35 UTC, elguardian approved these changes

2022-02-21 08:50 UTC, gmunozfe commented
jenkins retest this

2022-02-21 11:46 UTC, VaniHaripriya commented
> > If this is for testing, shouldn't it be at "test" folder instead of "main"?
> 
> Agree with you @gmunozfe , will move it to test folder.

@gmunozfe ,Prometheus Integration test can not access the class in test folder, as we are accessing jbpm-executor from drools-jbpm-integration through the dependency jar. So, leaving JobExecutionErrorCommand.java in main folder.

2022-03-03 18:04 UTC, merged