[JBPM-10053]-UserTaskInstanceWithCustomVarsQueryMapper not returning "COLUMN_TASK_SLA_DUE_DATE"
kiegroup/jbpm pull request #2135
Opened 2022-04-01 18:40 UTC by VaniHaripriya

Jira- https://issues.redhat.com/browse/JBPM-10053

Updated UserTaskInstanceWithCustomVarsQueryMapper with the missing column name- COLUMN_TASK_SLA_DUE_DATE

2022-04-03 20:38 UTC, gmunozfe requested changes
Compilation failure, could you check?

```
jbpm-kie-services: Compilation failure
19:13:10  [ERROR] /home/jenkins/workspace/KIE/main/pullrequest/jbpm-main.pr/bc/kiegroup_jbpm/jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/UserTaskInstanceDesc.java:[54,9] reference to UserTaskInstanceDesc is ambiguous
19:13:10  [ERROR]   both constructor UserTaskInstanceDesc(java.lang.Long,java.lang.String,java.util.Date,java.lang.String,java.lang.String,java.lang.Integer,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.Long,java.util.Date,java.util.Date,java.lang.Long) in org.jbpm.kie.services.impl.model.UserTaskInstanceDesc and constructor UserTaskInstanceDesc(java.lang.Long,java.lang.String,java.util.Date,java.lang.String,java.lang.String,java.lang.Integer,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.Long,java.util.Date,java.util.Date,java.util.Date) in org.jbpm.kie.services.impl.model.UserTaskInstanceDesc match
```

2022-04-04 14:24 UTC, VaniHaripriya commented
Jenkins retest this

2022-04-04 16:05 UTC, gmunozfe commented on jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/mapper/UserTaskInstanceWithCustomVarsQueryMapper.java
> +                getColumnDateValue(dataSetResult, COLUMN_TASK_SLA_DUE_DATE, index)//slaDueDate
Apart from that column, shouldn't we add the rest of missing ones?

```
getColumnStringValue(dataSetResult, COLUMN_SUBJECT, index),
getColumnStringValue(dataSetResult, COLUMN_CORRELATIONKEY, index), 
getColumnIntValue(dataSetResult, COLUMN_PROCESSTYPE, index),
getColumnIntValue(dataSetResult, COLUMN_TASK_SLA_COMPLIANCE, index)
```

@VaniHaripriya @fjtirado wdyt?

2022-04-04 16:06 UTC, gmunozfe reviewed
One question to add other columns and a request for having a test on this

2022-04-18 10:16 UTC, VaniHaripriya commented
Jenkins retest this

2022-04-25 07:51 UTC, gmunozfe commented on jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/TaskVariablesQueryServiceTest.java
> +    public void testUserTaskInstanceWithCustomVarsQueryMapperResult() throws Exception {
This test is part of an "ignore" annotated class, so won't be executed in CI. Anyway, you can keep it for reference

2022-04-25 08:01 UTC, gmunozfe requested changes
include also COLUMN_WORKITEMID and COLUMN_FORM_NAME

2022-04-25 08:01 UTC, gmunozfe commented on jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/mapper/UserTaskInstanceWithCustomVarsQueryMapper.java
> +                getColumnIntValue(dataSetResult, COLUMN_TASK_SLA_COMPLIANCE, index)//slaCompliance
Same here for COLUMN_WORKITEMID and COLUMN_FORM_NAME

2022-04-26 08:25 UTC, gmunozfe approved these changes
Looks good to me, well done @VaniHaripriya !

2022-04-26 11:51 UTC, fjtirado commented on jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/UserTaskInstanceDesc.java
> +
I think this files does not need to be modified, you can checkout previous version from history and commit

2022-04-26 12:32 UTC, fjtirado approved these changes

2022-04-27 10:00 UTC, fjtirado commented
jenkins retest this

2022-04-28 09:44 UTC, merged

2022-04-28 10:11 UTC, gmunozfe commented
@VaniHaripriya could you backport it to 7.67.x as well?