JBPM-10059 Aborted staged remains active in the process engine
kiegroup/jbpm pull request #2138
Opened 2022-04-07 09:13 UTC by bxf12315

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[https://issues.redhat.com/browse/JBPM-10059](https://issues.redhat.com/browse/JBPM-10059)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

2022-04-07 09:13 UTC, bxf12315 commented
@elguardian it's a draft code, please check it.

2022-04-08 08:55 UTC, elguardian commented on jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImpl.java
> +            if (activeNodes == null || activeNodes.size() == 0) {
I meant the other way round... not having active nodes does not mean is completed.

2022-04-08 09:14 UTC, bxf12315 commented on jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImpl.java
> +            if (activeNodes == null || activeNodes.size() == 0) {
new condition is if ((activeNodes == null || activeNodes.size() == 0) && ((CaseStageImpl) stagesByName.get(n.getNodeId())).isAutoComplete())

2022-04-11 06:59 UTC, elguardian commented on jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImpl.java
> +            if (activeNodes == null || activeNodes.size() == 0) {
you need to compute if a node is being completed or aborted. So far we have no way to know when a stage is being cancelled so my advice would be to check this line

'''
Collection<Long> completedNodes = nodes.stream().filter(n -> ((NodeInstanceDesc)n).getType() == 1).map(n -> n.getId()).collect(toList());
'''

and try to check if there are nodes in a different state as completed for instance (cancelled) if that happens you can see if you can set the status as cancelled or not

2022-04-25 08:03 UTC, gmunozfe commented
@bxf12315 test failures seem related

2022-05-09 13:10 UTC, bxf12315 commented
> @bxf12315 test failures seem related

WDYT?  if the way is. correct,  I will add some UT for it.

2022-07-26 19:30 UTC, gmunozfe requested changes
@bxf12315 I've added some comments and also a test for this scenario, you can check it out here:
https://github.com/gmunozfe/jbpm/tree/JBPM-10059_test

I'm not sure what is the expected behaviour when a Stage is cancelled. According to this implementation (and based on autocomplete flag), the StageStatus is Completed, however, it seems more accurate to have Canceled as StageStatus, no matter if it has "autocomplete" or not. @elguardian wdyt?

Besides, it doesn't seem a valid fix, as this doesn't cover those without autocomplete.

2022-07-27 12:31 UTC, bxf12315 commented on jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImpl.java
> +                                             adHocFragments, isAutoComplete));
I think maybe is not, you can see commit https://github.com/kiegroup/jbpm/commit/fa4c3e8d9e197ed5b6f073e6b4f866d5f5e939ec#diff-d8bc14ba30316578b3079d5469901b48ada98d8be18ddc7e2367f969bb60917aR44
now, the default value is true.

2022-08-25 07:03 UTC, afalhambra commented
@bxf12315 can this be closed? I can see a pr already merged for the same: https://github.com/kiegroup/jbpm/pull/2172

2022-08-25 08:41 UTC, closed without merging

2022-08-25 08:44 UTC, bxf12315 commented
sure