[JBPM-10094]- Current index settings might cause DeadLocks in SQL Server
kiegroup/jbpm pull request #2160
Opened 2022-07-05 20:07 UTC by VaniHaripriya

**JIRA**: https://issues.redhat.com/browse/JBPM-10094

Updated the index settings in SQL Server DDL Script-sqlserver-jbpm-schema.sql to resolve the DeadLocks in SQL Server under stress tests.

2022-07-05 22:01 UTC, VaniHaripriya commented
Jenkins retest this please

2022-07-06 06:41 UTC, afalhambra requested changes
@VaniHaripriya this requires changes for:

- [sql server 2008 scripts](https://github.com/kiegroup/jbpm/tree/main/jbpm-db-scripts/src/main/resources/db/ddl-scripts/sqlserver2008)
- [upgrade scripts](https://github.com/kiegroup/jbpm/tree/main/jbpm-db-scripts/src/main/resources/db/upgrade-scripts)

2022-07-06 15:32 UTC, VaniHaripriya commented
> @VaniHaripriya this requires changes for:
> 
> * [sql server 2008 scripts](https://github.com/kiegroup/jbpm/tree/main/jbpm-db-scripts/src/main/resources/db/ddl-scripts/sqlserver2008)
> * [upgrade scripts](https://github.com/kiegroup/jbpm/tree/main/jbpm-db-scripts/src/main/resources/db/upgrade-scripts)

@afalhambra Thank you Alberto,will make the changes.

2022-07-07 06:22 UTC, afalhambra reviewed
I think we should align the rest of the db schemas to be all aligned, otherwise we will end up having some discrepancies between them.
Other than that, it looks good to me

2022-07-07 18:29 UTC, fjtirado approved these changes

2022-07-08 07:56 UTC, fjtirado commented
> I think we should align the rest of the db schemas to be all aligned, otherwise we will end up having some discrepancies between them. wdyt @gmunozfe? Other than that, it looks good to me

@VaniHaripriya @afalhambra After taking a look at the jira description, I realize it will be good to do this index change to all schemas, because the problem is not specific to SQL, but related to the queries that are performed in any DB

2022-07-08 08:24 UTC, afalhambra commented
> > I think we should align the rest of the db schemas to be all aligned, otherwise we will end up having some discrepancies between them. wdyt @gmunozfe? Other than that, it looks good to me
> 
> @VaniHaripriya @afalhambra After taking a look at the jira description, I realize it will be good to do this index change to all schemas, because the problem is not specific to SQL, but related to the queries that are performed in any DB

+1

2022-07-13 13:40 UTC, afalhambra requested changes
Apart from the request changes it'd also be nice if you can add the following sql statement at the end of each create scripts locate in the [ddl60 folder](https://github.com/kiegroup/jbpm/tree/main/jbpm-db-scripts/src/test/resources/ddl60) for testing (it is not added in any other upgrade script, so tests will fail):

`create index IDX_EventTypes_element ON EventTypes(element);`

2022-07-14 09:31 UTC, afalhambra approved these changes
Looks good to me @VaniHaripriya 
Great job, thank you

2022-07-14 20:51 UTC, VaniHaripriya commented
> Looks good to me @VaniHaripriya Great job, thank you



> Looks good to me @VaniHaripriya Great job, thank you

Thank you @afalhambra.

2022-07-18 12:29 UTC, merged