[JBPM-9946] servicesorm.xml validation failure
kiegroup/jbpm pull request #2269
Opened 2023-02-08 21:37 UTC by fjtirado

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

2023-02-08 22:00 UTC, martinweiler requested changes

2023-02-08 22:00 UTC, martinweiler commented on jbpm-services/jbpm-kie-services/src/main/resources/META-INF/Servicesorm.xml
Can you restore the quotes? Without them, I get a validation error on https://www.freeformatter.com/xml-validator-xsd.html

2023-02-08 22:00 UTC, martinweiler commented on jbpm-services/jbpm-kie-services/src/main/resources/META-INF/Servicesorm.xml
>              SELECT A1.processInstanceId, A1.variableId, A1.value
Maybe the line numbers in RHPAM-4649 were incorrect (my bad, I should have double-checked), but the correct sequence order as per the xsd is named-query, named-native-query, sql-result-set-mapping. Therefore, please move <sql-result-set-mapping name="UserTaskInstanceDesc"> to the end of the file (after the last </named-native-query>). Thanks!

2023-02-09 15:42 UTC, gmunozfe approved these changes
Looks good to me, excellent work @fjtirado !

2023-02-09 15:49 UTC, martinweiler approved these changes
LGTM, thank you @fjtirado

2023-02-09 16:39 UTC, merged